package com.luisfelipesdn12.primes.exceptions;

public class PrimePositionZeroOrNegativeException extends RuntimeException {

    /**
     * DEFAULT SERIAL VERSION UID GENERATED BY VSCODE
     */
    private static final long serialVersionUID = 1L;
    
}